# Change these first
owner: CZQM-FIR # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Main Website
    url: https://czqm.ca
  - name: Overseer
    url: https://overseer.czqm.ca
  - name: Worker
    url: http://worker.czqm.ca/cron-health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.czqm.ca
  # baseUrl: /your-repo-name
  logoUrl: https://czqm.ca/_app/immutable/assets/CZQM-White.P2MAZOQj.svg
  favicon: https://czqm.ca/favicon.ico
  name: CZQM Uptime
  introTitle: "Status of the CZQM processes that run the FIRs tech"
  introMessage: See below information about our processes and their current status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/czqm-fir/core

assignees:
  - jackkoskie

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
